// 核团仅存在于左侧、右侧、中间、左右两侧
export const nucleusSideEnum = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  MIDDLE: 'MIDDLE',
  DOUBLE: 'DOUBLE',
}

// !现在的需求是，只要是表格里给了的那就用给的颜色，没给的就用随机。
const nucleusColors = [
  'rgba(37,115,167,0.8)',
  'rgba(173,51,39,0.8)',
  'rgba(190,103,0,0.8)',
  'rgba(21,174,174,0.8)',
  'rgba(140,190,0,0.8)',
  'rgba(20,144,120,0.8)',
  'rgba(202,164,12,0.8)',
  'rgba(128,61,156,0.8)',
  'rgba(62,85,205,0.8)',
  'rgba(195,186,107,0.8)',
  'rgba(11,132,0,0.8)',
  'rgba(190,0,91,0.8)',
  'rgba(101,101,101,0.8)',
  'rgba(191,104,103,0.8)',
  'rgba(165,85,121,0.8)',
  'rgba(186,186,186,0.8)',
  'rgba(80,95,118,0.8)',
  'rgba(150,99,54,0.8)',
  'rgba(152,82,65,0.8)',
]

export const getColorRandom = (num) => {
  if (num === undefined) {
    num = Math.round(Math.random() * (nucleusColors.length - 1))
  }
  const color = nucleusColors[num]
  return color
}

// 影像上传人员在上传时可供选择的核团列表为：
// 丘脑底核（STN）、内侧苍白球（GPi）、丘脑腹中间核（vim）、底丘脑后区（PSA）、
// 黑质(SN)、伏隔核（NAc） 、内囊前肢（ALIC）、未定带（Zi）、

const nucleusEnumList = {
  // 运动障碍性疾病
  0: [
    {
      zh: '左侧丘脑底核',
      en: 'Left STN',
      color: getColorRandom(0),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-STN.ply',
      simpleName: 'STN',
    },
    {
      zh: '右侧丘脑底核',
      en: 'Right STN',
      color: getColorRandom(0),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-STN.ply',
      simpleName: 'STN',
    },
    {
      zh: '左侧红核',
      en: 'Left RN',
      color: getColorRandom(1),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-RN.ply',
      simpleName: 'RN',
    },
    {
      zh: '右侧红核',
      en: 'Right RN',
      color: getColorRandom(1),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-RN.ply',
      simpleName: 'RN',
    },
    {
      zh: '左侧未定带',
      en: 'Left Zi',
      color: getColorRandom(2),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Zi.ply',
      simpleName: 'Zi',
    },
    {
      zh: '右侧未定带',
      en: 'Right Zi',
      color: getColorRandom(2),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Zi.ply',
      simpleName: 'Zi',
    },
    {
      zh: '左侧丘脑腹中间核',
      en: 'Left vim',
      color: getColorRandom(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Vim.ply',
      simpleName: 'vim',
    },
    {
      zh: '右侧丘脑腹中间核',
      en: 'Right vim',
      color: getColorRandom(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Vim.ply',
      simpleName: 'vim',
    },
    {
      zh: '左侧丘脑后下区',
      en: 'Left PSA',
      color: getColorRandom(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-PSA.ply',
      simpleName: 'PSA',
    },
    {
      zh: '右侧丘脑后下区',
      en: 'Right PSA',
      color: getColorRandom(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-PSA.ply',
      simpleName: 'PSA',
    },
    {
      zh: '左侧尾状核',
      en: 'Left Ca',
      color: getColorRandom(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Caudate.ply',
      simpleName: 'Ca',
    },
    {
      zh: '右侧尾状核',
      en: 'Right Ca',
      color: getColorRandom(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Caudate.ply',
      simpleName: 'Ca',
    },
    {
      zh: '左侧壳核',
      en: 'Left Pu',
      color: getColorRandom(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Putamen.ply',
      simpleName: 'Pu',
    },
    {
      zh: '右侧壳核',
      en: 'Right Pu',
      color: getColorRandom(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Putamen.ply',
      simpleName: 'Pu',
    },
    {
      zh: '左侧苍白球',
      en: 'Left GP',
      color: getColorRandom(7),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Pallidum.ply',
      simpleName: 'GPi',
    },
    {
      zh: '右侧苍白球',
      en: 'Right GP',
      color: getColorRandom(7),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Pallidum.ply',
      simpleName: 'GPi',
    },
    {
      zh: '左侧伏隔核',
      en: 'Left NAc',
      color: getColorRandom(8),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Accumbens-area.ply',
      simpleName: 'NAc',
    },
    {
      zh: '右侧伏隔核',
      en: 'Right NAc',
      color: getColorRandom(8),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Accumbens-area.ply',
      simpleName: 'NAc',
    },
    {
      zh: '左侧海马',
      en: 'Left Hippo',
      color: getColorRandom(9),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Hippocampus.ply',
      simpleName: 'Hippo',
    },
    {
      zh: '右侧海马',
      en: 'Right Hippo',
      color: getColorRandom(9),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Hippocampus.ply',
      simpleName: 'Hippo',
    },
    {
      zh: '左侧杏仁核',
      en: 'Left Amg',
      color: getColorRandom(10),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Amygdala.ply',
      simpleName: 'Amg',
    },
    {
      zh: '右侧杏仁核',
      en: 'Right Amg',
      color: getColorRandom(10),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Amygdala.ply',
      simpleName: 'Amg',
    },
    {
      zh: '左侧丘脑',
      en: 'Left Thalamus',
      color: getColorRandom(11),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Thalamus.ply',
      simpleName: 'Thalamus',
    },
    {
      zh: '右侧丘脑',
      en: 'Right Thalamus',
      color: getColorRandom(11),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Thalamus.ply',
      simpleName: 'Thalamus',
    },
    {
      zh: '脑干',
      en: 'Brainstem',
      color: getColorRandom(13),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'Brain-Stem.ply',
      simpleName: 'Brainstem',
    },
    {
      zh: '胼胝体后部',
      en: 'Posterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Posterior.ply',
    },
    {
      zh: '胼胝体中后部',
      en: 'Mid Posterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Mid_Posterior.ply',
    },
    {
      zh: '胼胝体中部',
      en: 'Central CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Central.ply',
    },
    {
      zh: '胼胝体中前部',
      en: 'Mid Anterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Mid_Anterior.ply',
    },
    {
      zh: '胼胝体前部',
      en: 'Anterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Anterior.ply',
    },
    {
      zh: '左侧小脑皮层',
      en: 'Left CB cortex',
      color: getColorRandom(14),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Cerebellum-Cortex.ply',
    },
    {
      zh: '右侧小脑皮层',
      en: 'Right CB cortex',
      color: getColorRandom(14),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Cerebellum-Cortex.ply',
    },
    {
      zh: '左侧小脑白质',
      en: 'Left CB WM',
      color: getColorRandom(15),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Cerebellum-White-Matter.ply',
    },
    {
      zh: '右侧小脑白质',
      en: 'Right CB WM',
      color: getColorRandom(15),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Cerebellum-White-Matter.ply',
    },
    {
      zh: '左侧黑质',
      en: 'Left SN',
      color: getColorRandom(16),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-SN.ply',
      simpleName: 'SN',
    },
    {
      zh: '右侧黑质',
      en: 'Right SN',
      color: getColorRandom(16),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-SN.ply',
      simpleName: 'SN',
    },
  ],
  // 精神性疾病
  1: [
    {
      zh: '左侧内囊前肢',
      en: 'Left ALIC',
      color: getColorRandom(12),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-ALIC.ply',
      simpleName: 'ALIC',
    },
    {
      zh: '右侧内囊前肢',
      en: 'Right ALIC',
      color: getColorRandom(12),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-ALIC.ply',
      simpleName: 'ALIC',
    },
    {
      zh: '左侧尾状核',
      en: 'Left Ca',
      color: getColorRandom(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Caudate.ply',
      simpleName: 'Ca',
    },
    {
      zh: '右侧尾状核',
      en: 'Right Ca',
      color: getColorRandom(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Caudate.ply',
      simpleName: 'Ca',
    },
    {
      zh: '左侧豆状核',
      en: 'Left Lenticula',
      color: getColorRandom(17),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Lenticula.ply',
      simpleName: 'Lenticula',
    },
    {
      zh: '右侧豆状核',
      en: 'Right Lenticula',
      color: getColorRandom(17),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Lenticula.ply',
      simpleName: 'Lenticula',
    },
    {
      zh: '左侧伏隔核',
      en: 'Left NAc',
      color: getColorRandom(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-NAc.ply',
      simpleName: 'NAc',
    },
    {
      zh: '右侧伏隔核',
      en: 'Right NAc',
      color: getColorRandom(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-NAc.ply',
      simpleName: 'NAc',
    },
    {
      zh: '左侧海马',
      en: 'Left Hippo',
      color: getColorRandom(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Hippocampus.ply',
      simpleName: 'Hippo',
    },
    {
      zh: '右侧海马',
      en: 'Right Hippo',
      color: getColorRandom(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Hippocampus.ply',
      simpleName: 'Hippo',
    },
    {
      zh: '左侧杏仁核',
      en: 'Left Amg',
      color: getColorRandom(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Amygdala.ply',
      simpleName: 'Amg',
    },
    {
      zh: '右侧杏仁核',
      en: 'Right Amg',
      color: getColorRandom(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Amygdala.ply',
      simpleName: 'Amg',
    },
    {
      zh: '左侧丘脑',
      en: 'Left Thalamus',
      color: getColorRandom(7),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Thalamus.ply',
      simpleName: 'Thalamus',
    },
    {
      zh: '右侧丘脑',
      en: 'Right Thalamus',
      color: getColorRandom(7),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Thalamus.ply',
      simpleName: 'Thalamus',
    },
    {
      zh: '脑干',
      en: 'Brainstem',
      color: getColorRandom(13),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'Brain-Stem.ply',
      simpleName: 'Brainstem',
    },
    {
      zh: '胼胝体后部',
      en: 'Posterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Posterior.ply',
    },
    {
      zh: '胼胝体中后部',
      en: 'Mid Posterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Mid_Posterior.ply',
    },
    {
      zh: '胼胝体中部',
      en: 'Central CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Central.ply',
    },
    {
      zh: '胼胝体中前部',
      en: 'Mid Anterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Mid_Anterior.ply',
    },
    {
      zh: '胼胝体前部',
      en: 'Anterior CC',
      color: getColorRandom(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      plyFileName: 'CC_Anterior.ply',
    },
    {
      zh: '左侧小脑皮层',
      en: 'Left CB cortex',
      color: getColorRandom(2),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Cerebellum-Cortex.ply',
    },
    {
      zh: '右侧小脑皮层',
      en: 'Right CB cortex',
      color: getColorRandom(2),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Cerebellum-Cortex.ply',
    },
    {
      zh: '左侧小脑白质',
      en: 'Left CB WM',
      color: getColorRandom(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Left-Cerebellum-White-Matter.ply',
    },
    {
      zh: '右侧小脑白质',
      en: 'Right CB WM',
      color: getColorRandom(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      plyFileName: 'Right-Cerebellum-White-Matter.ply',
    },
  ],
}

export function getNucleusEnum(diseaseName = 0) {
  // 生成下标，用于排序
  if (nucleusEnumList[0][0].orderIndex === undefined) {
    Object.keys(nucleusEnumList).forEach((key) => {
      nucleusEnumList[key].forEach((item, index) => {
        item.orderIndex = index
      })
    })
  }
  return nucleusEnumList[diseaseName]
}
