// 核团仅存在于左侧、右侧、中间、左右两侧
export const nucleusSideEnum = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  MIDDLE: 'MIDDLE',
  DOUBLE: 'DOUBLE',
}

const nucleusColors = [
  'rgba(37,115,167,0.8)',
  'rgba(173,51,39,0.8)',
  'rgba(190,103,0,0.8)',
  'rgba(21,174,174,0.8)',
  'rgba(140,190,0,0.8)',
  'rgba(20,144,120,0.8)',
  'rgba(202,164,12,0.8)',
  'rgba(128,61,156,0.8)',
  'rgba(62,85,205,0.8)',
  'rgba(195,186,107,0.8)',
  'rgba(11,132,0,0.8)',
  'rgba(190,0,91,0.8)',
  'rgba(101,101,101,0.8)',
  'rgba(191,104,103,0.8)',
  'rgba(165,85,121,0.8)',
  'rgba(186,186,186,0.8)',
  'rgba(80,95,118,0.8)',
  'rgba(150,99,54,0.8)',
  'rgba(152,82,65,0.8)',
]

const getColor = (num) => {
  if (num === undefined) {
    num = Math.round(Math.random() * (nucleusColors.length - 1))
  }
  const color = nucleusColors[num]
  return color
}

// 影像上传人员在上传时可供选择的核团列表为：
// 丘脑底核（STN）、内侧苍白球（GPi）、丘脑腹中间核（vim）、底丘脑后区（PSA）、
// 黑质(SN)、伏隔核（NAc） 、内囊前肢（ALIC）、未定带（Zi）、

const DiseaseEnum = {
  // 运动障碍性疾病
  PD: 0,
  // 精神性疾病
  SZ: 1,
}

const nucleusEnumList = {
  // 运动障碍性疾病
  [DiseaseEnum.PD]: [
    {
      zh: '左侧丘脑底核',
      en: 'Left STN',
      color: getColor(0),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-STN',
      simpleName: 'STN',
    },
    {
      zh: '右侧丘脑底核',
      en: 'Right STN',
      color: getColor(0),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-STN',
      simpleName: 'STN',
    },
    {
      zh: '左侧红核',
      en: 'Left RN',
      color: getColor(1),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-RN',
      simpleName: 'RN',
    },
    {
      zh: '右侧红核',
      en: 'Right RN',
      color: getColor(1),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-RN',
      simpleName: 'RN',
    },
    {
      zh: '左侧未定带',
      en: 'Left Zi',
      color: getColor(2),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Zi',
      simpleName: 'Zi',
    },
    {
      zh: '右侧未定带',
      en: 'Right Zi',
      color: getColor(2),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Zi',
      simpleName: 'Zi',
    },
    {
      zh: '左侧丘脑腹中间核',
      en: 'Left vim',
      color: getColor(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Vim',
      simpleName: 'vim',
    },
    {
      zh: '右侧丘脑腹中间核',
      en: 'Right vim',
      color: getColor(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Vim',
      simpleName: 'vim',
    },
    {
      zh: '左侧丘脑后下区',
      en: 'Left PSA',
      color: getColor(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-PSA',
      simpleName: 'PSA',
    },
    {
      zh: '右侧丘脑后下区',
      en: 'Right PSA',
      color: getColor(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-PSA',
      simpleName: 'PSA',
    },
    {
      zh: '左侧尾状核',
      en: 'Left Ca',
      color: getColor(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Caudate',
      simpleName: 'Ca',
    },
    {
      zh: '右侧尾状核',
      en: 'Right Ca',
      color: getColor(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Caudate',
      simpleName: 'Ca',
    },
    {
      zh: '左侧壳核',
      en: 'Left Pu',
      color: getColor(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Putamen',
      simpleName: 'Pu',
    },
    {
      zh: '右侧壳核',
      en: 'Right Pu',
      color: getColor(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Putamen',
      simpleName: 'Pu',
    },
    {
      zh: '左侧苍白球',
      en: 'Left GP',
      color: getColor(7),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Pallidum',
      simpleName: 'GPi',
    },
    {
      zh: '右侧苍白球',
      en: 'Right GP',
      color: getColor(7),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Pallidum',
      simpleName: 'GPi',
    },
    {
      zh: '左侧伏隔核',
      en: 'Left NAc',
      color: getColor(8),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Accumbens-area',
      simpleName: 'NAc',
    },
    {
      zh: '右侧伏隔核',
      en: 'Right NAc',
      color: getColor(8),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Accumbens-area',
      simpleName: 'NAc',
    },
    {
      zh: '左侧海马',
      en: 'Left Hippo',
      color: getColor(9),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Hippocampus',
      simpleName: 'Hippo',
    },
    {
      zh: '右侧海马',
      en: 'Right Hippo',
      color: getColor(9),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Hippocampus',
      simpleName: 'Hippo',
    },
    {
      zh: '左侧杏仁核',
      en: 'Left Amg',
      color: getColor(10),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Amygdala',
      simpleName: 'Amg',
    },
    {
      zh: '右侧杏仁核',
      en: 'Right Amg',
      color: getColor(10),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Amygdala',
      simpleName: 'Amg',
    },
    {
      zh: '左侧丘脑',
      en: 'Left Thalamus',
      color: getColor(11),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Thalamus',
      simpleName: 'Thalamus',
    },
    {
      zh: '右侧丘脑',
      en: 'Right Thalamus',
      color: getColor(11),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Thalamus',
      simpleName: 'Thalamus',
    },
    {
      zh: '脑干',
      en: 'Brainstem',
      color: getColor(13),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'Brain-Stem',
      simpleName: 'Brainstem',
    },
    {
      zh: '胼胝体后部',
      en: 'Posterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Posterior',
    },
    {
      zh: '胼胝体中后部',
      en: 'Mid Posterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Mid_Posterior',
    },
    {
      zh: '胼胝体中部',
      en: 'Central CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Central',
    },
    {
      zh: '胼胝体中前部',
      en: 'Mid Anterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Mid_Anterior',
    },
    {
      zh: '胼胝体前部',
      en: 'Anterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Anterior',
    },
    {
      zh: '左侧小脑皮层',
      en: 'Left CB cortex',
      color: getColor(14),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Cerebellum-Cortex',
    },
    {
      zh: '右侧小脑皮层',
      en: 'Right CB cortex',
      color: getColor(14),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Cerebellum-Cortex',
    },
    {
      zh: '左侧小脑白质',
      en: 'Left CB WM',
      color: getColor(15),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Cerebellum-White-Matter',
    },
    {
      zh: '右侧小脑白质',
      en: 'Right CB WM',
      color: getColor(15),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Cerebellum-White-Matter',
    },
    {
      zh: '左侧黑质',
      en: 'Left SN',
      color: getColor(16),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-SN',
      simpleName: 'SN',
    },
    {
      zh: '右侧黑质',
      en: 'Right SN',
      color: getColor(16),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-SN',
      simpleName: 'SN',
    },
  ],
  // 精神性疾病
  [DiseaseEnum.SZ]: [
    {
      zh: '左侧内囊前肢',
      en: 'Left ALIC',
      color: getColor(12),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-ALIC',
      simpleName: 'ALIC',
    },
    {
      zh: '右侧内囊前肢',
      en: 'Right ALIC',
      color: getColor(12),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-ALIC',
      simpleName: 'ALIC',
    },
    {
      zh: '左侧尾状核',
      en: 'Left Ca',
      color: getColor(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Caudate',
      simpleName: 'Ca',
    },
    {
      zh: '右侧尾状核',
      en: 'Right Ca',
      color: getColor(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Caudate',
      simpleName: 'Ca',
    },
    {
      zh: '左侧豆状核',
      en: 'Left Lenticula',
      color: getColor(17),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Lenticula',
      simpleName: 'Lenticula',
    },
    {
      zh: '右侧豆状核',
      en: 'Right Lenticula',
      color: getColor(17),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Lenticula',
      simpleName: 'Lenticula',
    },
    {
      zh: '左侧伏隔核',
      en: 'Left NAc',
      color: getColor(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-NAc',
      simpleName: 'NAc',
    },
    {
      zh: '右侧伏隔核',
      en: 'Right NAc',
      color: getColor(4),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-NAc',
      simpleName: 'NAc',
    },
    {
      zh: '左侧海马',
      en: 'Left Hippo',
      color: getColor(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Hippocampus',
      simpleName: 'Hippo',
    },
    {
      zh: '右侧海马',
      en: 'Right Hippo',
      color: getColor(5),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Hippocampus',
      simpleName: 'Hippo',
    },
    {
      zh: '左侧杏仁核',
      en: 'Left Amg',
      color: getColor(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Amygdala',
      simpleName: 'Amg',
    },
    {
      zh: '右侧杏仁核',
      en: 'Right Amg',
      color: getColor(6),
      visible: true,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Amygdala',
      simpleName: 'Amg',
    },
    {
      zh: '左侧丘脑',
      en: 'Left Thalamus',
      color: getColor(7),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Thalamus',
      simpleName: 'Thalamus',
    },
    {
      zh: '右侧丘脑',
      en: 'Right Thalamus',
      color: getColor(7),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Thalamus',
      simpleName: 'Thalamus',
    },
    {
      zh: '脑干',
      en: 'Brainstem',
      color: getColor(13),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'Brain-Stem',
      simpleName: 'Brainstem',
    },
    {
      zh: '胼胝体后部',
      en: 'Posterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Posterior',
    },
    {
      zh: '胼胝体中后部',
      en: 'Mid Posterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Mid_Posterior',
    },
    {
      zh: '胼胝体中部',
      en: 'Central CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Central',
    },
    {
      zh: '胼胝体中前部',
      en: 'Mid Anterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Mid_Anterior',
    },
    {
      zh: '胼胝体前部',
      en: 'Anterior CC',
      color: getColor(18),
      visible: false,
      nucleusSide: nucleusSideEnum.MIDDLE,
      downloadName: 'CC_Anterior',
    },
    {
      zh: '左侧小脑皮层',
      en: 'Left CB cortex',
      color: getColor(2),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Cerebellum-Cortex',
    },
    {
      zh: '右侧小脑皮层',
      en: 'Right CB cortex',
      color: getColor(2),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Cerebellum-Cortex',
    },
    {
      zh: '左侧小脑白质',
      en: 'Left CB WM',
      color: getColor(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Left-Cerebellum-White-Matter',
    },
    {
      zh: '右侧小脑白质',
      en: 'Right CB WM',
      color: getColor(3),
      visible: false,
      nucleusSide: nucleusSideEnum.DOUBLE,
      downloadName: 'Right-Cerebellum-White-Matter',
    },
  ],
}

export function getNucleusEnum(diseaseEnum = 0) {
  // 生成下标，用于排序
  Object.keys(nucleusEnumList).forEach((key) => {
    nucleusEnumList[key].forEach((item, index) => {
      item.orderIndex = index
    })
  })
  return nucleusEnumList[diseaseEnum]
}
